### ISSUE TITLE
problem since last update...

### ISSUE THREAD

**Issue by mikesatv2** [fastcolors/skin.sio2#13]
using apple tv2 with sio2 skin as I always have... their last update finally fixed my keyboard, which did not display letters as you typed... now I loaded simple iptv client with remote paths for channels and epg, then went to home page customizer and add/turned on the "live TV" button and when I go to it its just blank (excerpt a TV icon). clicked all buttons thinking it'd bring up a view menu; but it does nothing... why is it blank? what do I have to change? is it the sio2 code?

also, switched skin back to default, clicked "live TV" and all shows and works great... :/

**Comment by fastcolors** [comment]
can you please let me know what Kodi version are you on?

also can You explain the issue a little clearer?
the icon is not there? the icon on main menu doesn't open anything?

hope we'll succeed in fixing this.

**Comment by mikesatv2** [comment]
it's 14.2

I can turn the "live TV" button, and displays on home, then you click it...it opens the open/welcome screen that I'm in the correct mode... but no menu, channel list, etc.  left, right, up, down commands do nothing... if I change skin back to the kodi default one, my channel list is there and works.  additionally, the last sio2 version (before last update two months ago) worked fine.... so its definitely something in that last v3.x update.  :/

thanks so much for the reply....
