### ISSUE TITLE
Problem with translation of Power icon label

### ISSUE THREAD

**Issue by Yann-R** [fastcolors/skin.sio2#14]
Hello,

We encounter a problem to translate the Power icon label (which is "Off" in English).
It seems that skin.sio2 re-uses the string msgctxt "#351" of kodi-core to this end.

Nevertheless reusing that string seems not to be a perfect idea.
Originally this strings is used (for several settings options) to indicate if they are selected by the user or not (On or Off) and in some language this can be correctly translated into something that has nothing in common with "Power" Off. (For instance iPhone in French now translates On/Off switches in settings simply into Yes/No, which is very acceptable).

So I guess that the best would be for skin.sio2 to reuse another existing string really associated to Power off (like "Shutdown" for instance) or define its own string for that new label.
Best regards.

**Comment by fastcolors** [comment]
will fix!

**Comment by Yann-R** [comment]
Great. Thank you!
(I'll pay attention to the coming fix).

**Comment by Yann-R** [comment]
Oups... 
I just noticed this issue should probably have been submitted to the "new" repository skin.sio2x
( https://github.com/fastcolors/skin.sio2x/issues ). Or maybe do you prefer we use the Kodi forum section of Kodi for skin SiO2? ( http://forum.kodi.tv/forumdisplay.php?fid=206 )

**Comment by fastcolors** [comment]
this will be fixed in ATV4 Krypton release, Sio2x will probably be abandoned, and some features be ported backward to sio2. Sorry for the huge huge delay in coding this, but Life has been taking over thi year. I'm back now ;-)

**Comment by fastcolors** [comment]
https://github.com/fastcolors/skin.sio2/commit/c3836fc2e7d1dbcc0a1d999890cc74afb86db193

**Comment by fastcolors** [comment]
plz check if that makes sense and I'll close this!

**Comment by Yann-R** [comment]
I'll try to check asap is the string 33060 is better than the string 351.
But for now, I can't tell since I don't know what is their content.

**Comment by Yann-R** [comment]
Checked (351="Off", 33060="Power"). Perfect!
Thanks.
