### ISSUE TITLE
Problem with translation of Settings sub-menu

### ISSUE THREAD

**Issue by Yann-R** [fastcolors/skin.sio2#15]
Hello,

We encountered a small problem with the translation of the two strings that are displayed as sub-menu for the Settings icon from the home screen, appearing like this in English:

```
General Settings
  Skin settings
```

It seems that the first menu item is built from two existing strings in kodi-core: "General" + "Settings". (Note: that explains the uppercase 'S' in Settings that is not present in the second menu item).
Unfortunately, the correct order of these two words is not the same in every language and may be not correct at all when you concatenate translation(General) + translation(Settings).

I suggest you could use different other options, allowing a correct translation in any language:
1. re-use the existing string meaning globally the same thing: "Settings - General"
   (but the 1st menu item would not have the same style as the 2nd label as "Skin settings")
2. concatenate the existing strings, for both the menu items, using a separator
   "Settings" + ": " + "General"
   "Settings" + ":" + "Skin"
3. define your own new string for "General settings" (which would correct the S)
4. re-use simply "General" and "Skin" strings in the sub-menu (without the word "settings")
5. other solution...?

Do you think this would be possible?
Best regards.

**Comment by fastcolors** [comment]
https://github.com/fastcolors/skin.sio2/commit/06aee59e1e3d3fa6fb4e9a48bb2a9c1a7c9f156e

**Comment by fastcolors** [comment]
I used "System Setting" does that work?
check and I can close this!

cheers, and again.. I know one whole year is a little too much time :-(

**Comment by Yann-R** [comment]
I see you've chosen option 5 "other solution" ;-)
Yes, I guess re-using this full string "System Settings" that already exists is perfectly OK
(the translators have already translated this in their languages correctly).
Thanks.

**Comment by fastcolors** [comment]
<3
