### ISSUE TITLE
ATV4 -  MyPVRGuide 

### ISSUE THREAD

**Issue by gsulshski** [fastcolors/skin.sio2#16]
I have tested the ATV4 LiveTV  for Si02 skin on Jarvis  and I have the following feedback:

I don't have an ATV4 so I don't know what the UI/Experience is suppose to be like.

MyPVRGuide.xml has the following problems from my perspective.
- Channel
  Channel number only has space for 2 digits  
  Channel name is gray on gray
  Duration is gray on gray.

I have an update that I like to the MyPVRGuide.xml that addresses these items above if you are interested.

I also have an update that has some translucent colors to the genres for better readability of the EPG and have a set of colors (0.png, .....240.png).  Not sure if this is something you are interested in and I don't know the "color schema"  of an ATV4.

Also problems noted:

EPG:

  The background for the timeline has XBMC written vs Kodi  or something else
  The timeline is centered on a 1/2 hr but the timeline only shows the 1hr markings which can confuse the user on what time is it
 *\* If you select a station, no channel is brought up making this view non-functional in that you can't start a channel   **
  The font and color of the actual timeline 8:00pm ...etc could be lighter and larger ?

EPG Now and Next: 

```
In the SIO2x skin,  I never used or even saw these views.
```

   I think you want them to look like TV Channel view while they have no real substance at the moment.

**Comment by gsulshski** [comment]
I have tested the ATV4 LiveTV for Si02 skin on Jarvis and I have the following feedback:

I don't have an ATV4 so I don't know what the UI/Experience is suppose to be like.

TV channel:

When you scroll down the TV channel view, the page number pops up but it is black so that you can't read the number and it is placed in an odd spot on the screen

**Comment by gsulshski** [comment]
I have some testing feedback on Recordings, Timers  with potential fixes.

I have some testing feedback for TV shows and Music.

Let me know if you are interested

**Comment by fastcolors** [comment]
i assolutely am, sorry for the delay life has been taking over this past year.

I already fixed some pvr issue, if you still willing to test the skin, i'd be more than happy to get your feedbacks, again. sorry but i've been dealing with life and has NO time for this...
