### ISSUE TITLE
additional icons ATV style

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#18]
Here are some ATV icons to use in this skin, quality isn't fantastic but they look the part
[icons.zip](https://github.com/fastcolors/skin.sio2/files/687439/icons.zip)

**Comment by fastcolors** [comment]
i was in the process of fixing some.. just remade Music one, and dowloaded from Apple SDK!
got the zip will look and get back!

PS welcome to coding heaven ;)

**Comment by fastcolors** [comment]
Music one is the old one, and I think using the "iTunes" ones isn't really what we want for Kodi... some of them are exactly the same as the ones I did, like addons and programs (i think you got them from a mod)

all icons should be 300x180 and possibly without jpeg artefacts..

extra ones are cool, I had the same idea, so if you'd like to gather some you could screenshot those appearing on http://www.apple.com/tvos/

<img width="1106" alt="schermata 2017-01-05 alle 16 10 45" src="https://cloud.githubusercontent.com/assets/2766945/21685355/912314a6-d361-11e6-9dc1-b24b8c271c91.png">

I can then cut them into shape.
then we need to point directory search to them!

**Comment by fastcolors** [comment]
https://github.com/fastcolors/skin.sio2/commit/82b0b7bbee3eb8f943aa13273b46cfa79dfa7ddb

**Comment by fastcolors** [comment]
I think it would be very good to make an external addon for this so the skin size doesn't grow exponentially... we should start gathering the icons, i'll take care of setting the repo up, then pushing updates will be easy!

**Comment by fastcolors** [comment]
further improvements on

https://github.com/fastcolors/resource.images.sio2.icons
