### ISSUE TITLE
invisible text in a few pages

### ISSUE THREAD

**Issue by fastcolors** [fastcolors/skin.sio2#23]
file manager and maybe elsewhere

**Comment by steverae68** [comment]
![screen shot 2017-01-07 at 12 46 13 2](https://cloud.githubusercontent.com/assets/17755581/21741771/5c1c6dd4-d4d8-11e6-898e-9e07af4d2941.png)

Here is the file manager :(

**Comment by fastcolors** [comment]
can you try latest build?

if fixed I'll close this.
are there any other invisible test pages?

**Comment by fastcolors** [comment]
i'll close this... if any other text issue pops, feel free to reopen it, or open a new one...
