### ISSUE TITLE
Add TVOS Gui sounds and TVOS screensaver as dependancies when loaded

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#24]
There are two additional TVOS add ons available

https://github.com/MrLegendary/resource.uisounds.tvos/blob/master/addon.xml

Screen savers

https://github.com/enen92/screensaver.at...master.zip

**Comment by fastcolors** [comment]
uisounds will need to be packed into sio2 addons (naming conformity is always good)
will take care of those last.

screensavers I don't know if including them at install is good, I could add a "do you want ATV screensaver?" optional install window.

but to be honest I tried those and they are really resource consuming, plus many hardware already handles ATV style screensaver at top level.. but I think adding the optional download is easily doable.

will handle this when skin is 99% ready.

**Comment by fastcolors** [comment]
added guisounds.
