### ISSUE TITLE
pinwheel needs to be reduced in size

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#27]
As it says above, the pinwheel (or loading wheel) needs to be reduced in size

**Comment by fastcolors** [comment]
do you have a screenshot of the size it should be?

**Comment by steverae68** [comment]
nope as i'm at work ;)  

Just smaller, i'll try and grab a screen shot from internet...
![screen shot 2017-01-09 at 01 17 25](https://cloud.githubusercontent.com/assets/17755581/21755280/66054a14-d609-11e6-8e41-8f294de31f23.png)

**Comment by fastcolors** [comment]
will not add the Loading... text since it seems to change for different items depending on what's being open.. just tested on my ATV, so i'll leave it kody way.

please test.

**Comment by steverae68** [comment]
Spot on :)   Thanks
