### ISSUE TITLE
Test of textures

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#28]
Here is the screen shot of the test build you sent me.....

![screen shot 2017-01-08 at 21 28 10](https://cloud.githubusercontent.com/assets/17755581/21753854/584d80a6-d5ed-11e6-8a85-4b8a676f9bdd.png)

**Comment by fastcolors** [comment]
i'll have my repo back up soon, already fixed this issue, will send you a zip file asap.
