### ISSUE TITLE
TV Shows top shelf layout

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#29]
![img_0152](https://cloud.githubusercontent.com/assets/17755581/21753894/0c12281c-d5ee-11e6-9ba3-b7035b45d82a.JPG)

This is what i meant by top shelf

**Comment by steverae68** [comment]
What we have now is the new TV App view
![screen shot 2017-01-08 at 22 07 18](https://cloud.githubusercontent.com/assets/17755581/21754361/6b3b1936-d5f6-11e6-8551-6177db1de145.png)

This is good but the bottom information line should show the TV show title, not the episode title (as seen above) 

This is what we currently have.....

![screen shot 2017-01-08 at 22 05 38](https://cloud.githubusercontent.com/assets/17755581/21754366/859f6b6a-d5f6-11e6-878b-74415d79fded.png)

**Comment by fastcolors** [comment]
fixed now showing TVshow titles not Episode Title ;)
