### ISSUE TITLE
Weather shelf background 

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#30]
Would it be possible to have the background on the shelf match the current conditions? Also, switch locations there too? If this is done than the information in the weather menu would now uneeded but it would be an excellent place the show the various weather maps available. 
Let me know if this makes sense or not.

**Comment by fastcolors** [comment]
yes it makes sense... will work on this a little later.

**Comment by fastcolors** [comment]
please test ;-)

**Comment by scrolling101** [comment]
That's the idea, however, it seems to be alternating through each day of the week. Could be set up to show only the current weather conditions?

**Comment by fastcolors** [comment]
> That's the idea, however, it seems to be alternating through each day of the week. Could be set up to show only the current weather conditions?

it's a demo showing all the images, when we have all of the backgrounds we want I'll stop the "demo mode" and just show 1.

right now it cycles through every item in the backdrop folder

;-)

**Comment by scrolling101** [comment]
Makes sense.

**Comment by fastcolors** [comment]
If you find any backdrop set that's cool let me know and we'll try some, I'll stop the cycle when we have the final one ( probably stop it before and remake it spin when we/if it changes)

**Comment by scrolling101** [comment]
I found these by icanuck. I think that they will go well with your shin. What do you think?
[weather1.zip](https://github.com/fastcolors/skin.sio2/files/698053/weather1.zip)

**Comment by scrolling101** [comment]
Had to break it up in to two files
[weather2.zip](https://github.com/fastcolors/skin.sio2/files/698054/weather2.zip)

**Comment by fastcolors** [comment]
I'll put them in for testing...

anyway I need to know if He made them himself or got them elsewhere in order to proper credit the maker.

Thanks for your help!!

**Comment by scrolling101** [comment]
I emailed iConuck

**Comment by fastcolors** [comment]
would be nice to get them @1920x1080 (doesn't really matter the height) so i can crop them @1920x720

then see the overall weight, since back in the days when I made first version of sio2 i had some full resolution but the skin was too heavy 40mb or so...

**Comment by scrolling101** [comment]
After looking at both set of pictures I think I like the ones you had originally.

**Comment by fastcolors** [comment]
me too. I'm gonna leave this open in case we find better ones...

**Comment by scrolling101** [comment]
What do you think of these?
[weather1.zip](https://github.com/fastcolors/skin.sio2/files/728472/weather1.zip)

**Comment by scrolling101** [comment]
[weather2.zip](https://github.com/fastcolors/skin.sio2/files/728477/weather2.zip)

**Comment by fastcolors** [comment]
i did a mix'n'match of the old and the new packs.. I also noticed some are are the same ones... pretty satisfied with what we got now... please test. I activated the cycling images just for testing purposes

**Comment by scrolling101** [comment]
Yeah, I used the existing ones as a base line and want through the list searching for other pictures. When I found a weather picture I liked I replaced it with the new one.

**Comment by fastcolors** [comment]
what do you think of what we got now? check and we'll try to bring this to a final! ;-)

**Comment by scrolling101** [comment]
I think it's a good assortment of pictures. I like them and yes we can close this issue.
