### ISSUE TITLE
Wrap artists names and album titles

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#32]
When in the music menu and it's set to icon display the artists names and album titles overlap. Would it be possible to have the text wrapped?

**Comment by fastcolors** [comment]
do you have a Library for music or are you in music files?

I just remade the music library view and doesn't support the view changes.. could you screenshot this issue with skin settings >debug on?

thanks!

**Comment by fastcolors** [comment]
ok I think I saw the issue!

**Comment by fastcolors** [comment]
fixed

please test

**Comment by scrolling101** [comment]
Perfect
