### ISSUE TITLE
Recommended option on top shelf not populating

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#36]
Ive been playing around with the top row of icons and have found i can add a shortcut to a section of a plugin (say salts trending movies) and it shows the movie posters on the top shelf.  This is awesome as it means it will change as trending movies change and i don't need to worry about updating my library manually.

with TV shows, i'd like to do the same thing, so i removed the TV Shows icon and created a new one pointing to the My Next Episodes option from salts which is linked to my trait.tv account and tells me which episode I'm up to in a particular season. 

I would love to be able to set this section top shelf view to show the tv show layout as we've discussed before ? Is this possible ?  at the moment i get this ...

![screen shot 2017-01-09 at 12 20 04](https://cloud.githubusercontent.com/assets/17755581/21766471/ad7517d2-d666-11e6-885c-fa7a8042f53a.png)

not very pretty at all :( 

would be nice to be able to set each of the 5 top shelf item views independently

**Comment by fastcolors** [comment]
will look into this, but it might be hard to make since plugins set the content of the list... and making dependencies for all existing plugins could be hard.

will try

**Comment by fastcolors** [comment]
just to know...

why not use included Recommended option for tv shows?

**Comment by steverae68** [comment]
because when i select the recommended option, it does not list anything.  my library is populated from trakt subscriptions but I've always had to use the My Next Episodes option from which ever plugin is linked to my trakt account.

i'm sure there was a version of your skin modded by someone, may have been an early version of TVOS by icanuck that let you choose the display type for tv shelf, i think it may have used skin helper plugin or something.... i'll try and find it.

**Comment by steverae68** [comment]
Just selected Recommended and OMG .... it works !!!!! you can close this issue - i'm, almost as happy as when i found out you can set the default play option to display the info page :)

**Comment by steverae68** [comment]
Yfresh install didn't fix it, still showing blank top shelf when recommended is choosen

**Comment by steverae68** [comment]
I've just been playing with this and god damn the recommended option works exactly as my ext episodes ..... that's nearly as good a revelation as when I found out you could set the information screen to be the default play option..... 

This works perfectly on my ATV but on my iMac, I just get a blank tv shelf when I have recommended set :(

Gonna reinstall skin and try again

**Comment by steverae68** [comment]
fixed, it, i installed skin.helper server and skin widgets then removed and reset the tv shows menu option and it now works :)

**Comment by fastcolors** [comment]
great!!
