### ISSUE TITLE
New backgrounds for light and dark modes as promised

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#37]
[backgrounds.zip](https://github.com/fastcolors/skin.sio2/files/693985/backgrounds.zip)

**Comment by fastcolors** [comment]
very nice, where did you find these?

is there a supposedly "default" one?

**Comment by steverae68** [comment]
There were ripped out of the tvOS emulator (part of Xcode) 

Cat get anything else, had to screen grab each one :)

**Comment by fastcolors** [comment]
good ones!
