### ISSUE TITLE
Can only see five rows of short cuts on home screen

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#39]
When customizing the home screen you can add as many short cut as you want. But Only able to see on more than five rows on the home screen.

**Comment by fastcolors** [comment]
doesn't it scroll at bottom? should work scrolling... not pretty but everything should be visible...

will investigate!

**Comment by fastcolors** [comment]
ok, I limited the amount of items to 30... should be enough..

or do I feel You want me to go 35? ;-)

**Comment by fastcolors** [comment]
please test

;-)

**Comment by scrolling101** [comment]
Works great
