### ISSUE TITLE
Recommended setting for movie and tv shows shelf

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#40]
When navigating from either movies or tv shows to the shelf display setting. If it's set to Recommend it doesn't populate the shelf and you get locked out from changing it. The only way to get out of it is to enable the mouse and click on it to change it.
![2017-01-10 22_25_40-kodi](https://cloud.githubusercontent.com/assets/24968671/21836800/211457d8-d785-11e6-893e-0ef45416c907.png)

**Comment by fastcolors** [comment]
can you try resetting the skin?

sorry I know that's a pain in the a$$, but I need tested if at first install the skin returns recommended or not, and I got to find if there's any way of disabling recommended in case the playlist is empty... but not sure if this can be done... mmmmmm

**Comment by fastcolors** [comment]
should be fixes with latest commit

**Comment by steverae68** [comment]
Tested and seems to work as expected now

**Comment by fastcolors** [comment]
great. closing this! :)
