### ISSUE TITLE
White flash in dark mode

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#41]
Every time you switch to another window (back or forth) there's this quick white flash/transition. Seems it's the same as in the default bright skin mode and just needs to be adjusted to match the dark mode.

**Comment by fastcolors** [comment]
i believe it's due to the background not been properly set.

will try to fix it asap!

**Comment by fastcolors** [comment]
please test

**Comment by badrabbit** [comment]
Fixed! Thanks a lot!

**Comment by fastcolors** [comment]
thank you for pointing out the bug!
