### ISSUE TITLE
latest build 608b39d- main menu icons down function anymore

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#42]
Latest commit 608b39d  3 hours ago @fastcolors fastcolors back to custom choice windows + view names fix

With this build, the settings, media sources, live tv and add ons buttons on main screen don't launch anything anymore

**Comment by scrolling101** [comment]
The same with search and settings.

**Comment by steverae68** [comment]
the only ones that seem to work are Movies, TV Shows, Add-ons and Programs oh and Quit.  This means you can't change any aspect of the skin.  Only way to get back it to delete the skin file from addons so kodi reverts back to default estuary skin......

**Comment by fastcolors** [comment]
my bad, forgot to check a couple of very important files when pushed update!!

sorry!
