### ISSUE TITLE
Media source

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#44]
The dialog screen that comes up when adding a source. The way it's laid out it looks like there should an icon of the content add-on.
![2017-01-07 12_12_13-kodi](https://cloud.githubusercontent.com/assets/24968671/21918995/398efc1a-d914-11e6-87dd-ad0b241ed6aa.png)

**Comment by fastcolors** [comment]
Kodi unified Dialogsettings.xml for various usecases, I probably need to be redoing this window, since it looks awful in Fullscreenplayback too..

definite something that needs remaking!

PS: the control for showing the icon is there, but not always there's something to show. 

will work on it.

**Comment by fastcolors** [comment]
this should be fixed ;-)

**Comment by scrolling101** [comment]
I like it.
