### ISSUE TITLE
A request that comes from the wife.

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#51]
Would it be possible to add mmpa rating to the movies view?

**Comment by fastcolors** [comment]
of course!!!

**Comment by fastcolors** [comment]
wives requests are aways top priority... ahaha i know how they get <3

**Comment by fastcolors** [comment]
all of the movies view i imagine?

**Comment by fastcolors** [comment]
plz test... i didn't add it to icon view since actually nothing is shown there... but if the Lady wants i'll code it in, or add a way to instantly know where not to click.

**Comment by scrolling101** [comment]
I'll run by the misses. 
Thank you

**Comment by fastcolors** [comment]
can I close this?

**Comment by scrolling101** [comment]
Yes
