### ISSUE TITLE
Remove the "TV Releases" and "MOVIE Releases" items from default menu - Not necessary

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#52]
Just my 2 pennies worth, but i think these are unnecessary as these functions can be custom set.
Plus, they use the extendedInfo plugin which is not compatible with the ATV (apparently, as it uses calls to functions that are blocked in TVOS).

This is just my opinion and i appreciate other comments to get a overall vote.....

**Comment by fastcolors** [comment]
yep i leave them only because i use them to send calls to couch potato & sickrage to get new stuff, and that's the only reason they're there by default, because I code different actions for those items..
