### ISSUE TITLE
Movie Information window

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#54]
When in the information view of a movie. I can't seem to navigate to either "Refresh" or "Choose art". Also, in the boxed area I remember there being other movie titles there.
![2017-01-22 14_01_21-skin sio2_1080i at atv4-krypton fastcolors_skin](https://cloud.githubusercontent.com/assets/24968671/22186004/89da0c10-e0ac-11e6-8c99-2baadabb73ae.png)

**Comment by scrolling101** [comment]
One more thing. When dark theme is set it's difficult to read both the time and ratings

**Comment by fastcolors** [comment]
everything should be fixed, I rely now on extended info for movies suggestions.. don't know if it best, since it's a little slow filling and.. well not all the movies are in library... but on the other hand you get suggestions on "what to get next"... what do you guys think??

**Comment by scrolling101** [comment]
👍
