### ISSUE TITLE
Multiple info screens

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#57]
I noticed that there was info in two places. To stream line things would it be possible to remove one? Personal it’s easier to select “I” and then and the video info pops up on screen.  However, I like the simplicity of the pull-down info screen. For example, if the back ground was gray, the orange text white and having the fanart.
![2017-01-24 21_45_49-2017-01-24 21_43_54-kodi](https://cloud.githubusercontent.com/assets/24968671/22278488/145c75be-e281-11e6-8d2d-45853f39af32.png)

![2017-01-24 21_47_12-](https://cloud.githubusercontent.com/assets/24968671/22278501/33f4e280-e281-11e6-8b5e-01c41a8d8aab.png)

**Comment by fastcolors** [comment]
test :-)

**Comment by scrolling101** [comment]
Looks really good.
