### ISSUE TITLE
location of show rating and unwatched label

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#59]
Would it be possible to locate both the rating and unwatched label to better accommodate square and rectangle posters?
![2017-01-24 22_08_54-kodi](https://cloud.githubusercontent.com/assets/24968671/22278648/518fa4be-e282-11e6-9956-e12a5fc20e37.png)

**Comment by scrolling101** [comment]
Actually after navigating around could we remove the rating? It would better align with the rest of the skin.

**Comment by fastcolors** [comment]
where did you get the square poster? is there a scraper for those?

this definitely needs fixing..

**Comment by scrolling101** [comment]
ITunes

**Comment by fastcolors** [comment]
iTunes scraper in kodi... mmm not following. :-(

**Comment by scrolling101** [comment]
I got it from iTunes awhile ago. Kodi didn't scrape it.

**Comment by fastcolors** [comment]
plz test maybe post a screenshot of how it looks with square posters

**Comment by scrolling101** [comment]
It look good. However, since most people use the traditional covers may be it should be moved over to the corner of it instead.
![screenshot000](https://cloud.githubusercontent.com/assets/24968671/22491672/62d232d6-e7e2-11e6-9a23-14d13b38ae3b.png)
![screenshot001](https://cloud.githubusercontent.com/assets/24968671/22491678/6db3d22c-e7e2-11e6-8a6a-9bf96c3b3dd5.png)

**Comment by scrolling101** [comment]
Thanks
