### ISSUE TITLE
Watched show doesn't update in library when watched via top shelf

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#62]
Hi

This may be just me but I've noticed that if i select an TV episode to watch say from the Up Next top shelf, when it finishes it does not update that it has been watched, unless i manually mark it as watched from the context menu.

don't know if it's just me and the way i have my library setup but i use trakt with the trakt plug in and this doesn't register a scrabble when i view an episode from the top shelf but if i navigate through my library to the same show and watch it there, it does.....

**Comment by fastcolors** [comment]
I believe it's a Kodi issue... i think it happened some times in the past too... for a while the same was happening, then they fixed it.. My skin only calls for play, so i don't see how it could avoid increasing the play count.. but i'll check if I did some weird stuff ;-)

**Comment by steverae68** [comment]
I've sent you an email if you can help me amend your code for my own personal thing, let me know if you get the email

Thanks

**Comment by fastcolors** [comment]
no emails on my side..

**Comment by steverae68** [comment]
Sent the email to your gmail account, i'll also sent it as a pm on kodi forum :)
