### ISSUE TITLE
TV show shelf "New Episode"

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#64]
Does "New Episode" always show up on the TV show shelf? Because it's always shows up as new whether or not  new or has been watch.

**Comment by fastcolors** [comment]
https://github.com/fastcolors/skin.sio2/commit/82e2ef84e043f4fd69ae491c8b4abd458ef99ce0

**Comment by fastcolors** [comment]
should be fixed, please test.. :-)

I believe there are some issues with play count starting episodes from shelf, but i'm not sure since I haven't tested that yet

lemme know.

cheers.
if this is fixed please close.

**Comment by steverae68** [comment]
This seems to work for me now anyway.
