### ISSUE TITLE
Custom Shelf items for each menu option e.g., posters, episodes, square etc etc

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#65]
Hi

If i create a custom home menu icon and point it at say a list of tv episodes, the top shelf displays the tv show icon as expected but it displays the name of the episode, how hard would it be to show the episode/series number instead.

if you point me in the right direction i can alter this code myself for my personal taste :)

FYI, using exodus linked to Trakt and the info I'm pulling is the New episodes list, this is instead of using the build in library :)

**Comment by fastcolors** [comment]
you need to mess with Includes_shelf.xml >>> PosterShortcutsCommons is the include you want to mess with, but beware that it will change also the naming for movies and everything  on shelf that is shown in a "poster" view.

**Comment by fastcolors** [comment]
i have no idea what exodus is... but I fear it's a "bad" addon ;-)

**Comment by fastcolors** [comment]
off topic.. how do you keep Kodi on ATV4 longer than 7 days?

**Comment by steverae68** [comment]
the personal 'free' developer account supplied by apple only lasts for 7 days. Then you have to resigns your app and reinstall.   Only way around this is to pay for the dev account  -  £79 for a year, i'd highly recommend it :)

**Comment by steverae68** [comment]
thanks for the tip re the code, i'll have  tinker with it and see what i can come up with :)

Exodus is a 'bad' plugin so lets not mention this anymore 👍

**Comment by steverae68** [comment]
OK I think I've solved my problem with a little bit of digging.
I found the part in the includes_shelf xml that displays the item title on the top shelf under the poster and changed this from ItemList.Title to ItemList.label which is what is used in the Biglist xml view and it does exactly what i want, shows the episode and season with the name as its pulling from an episode list.

This change also does not effect the tv shows season view :)

![screen shot 2017-02-05 at 12 39 54](https://cloud.githubusercontent.com/assets/17755581/22626198/54d3a9fa-eba0-11e6-8673-b3c8df4ba07e.png)

![screen shot 2017-02-05 at 12 40 16](https://cloud.githubusercontent.com/assets/17755581/22626200/5d434578-eba0-11e6-9b09-b9d2f33cf7b6.png)

**Comment by steverae68** [comment]
still wonder if its possible to specify what type of to-shelf item you have displayed for each icon.
for example, when you create the custom home button icons via the skin settings skin.shortcuts menu, is there not a way to say for this item i want to show posters, for this item i want to show episodes, for this item i want to show square etc etc
