### ISSUE TITLE
Lost access to Add On Manager in Newest build :(

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#66]
As above, no longer able to access Add On Manager to install new add ons from the add on menu since the latest update, only options from the menu now are video add ons, music adding, programs and cancel

**Comment by fastcolors** [comment]
addon manager is now App Store ;-) thought it made more sense to have a separate "install" item of the menu, this way if you are content with what's installed you could hide Appstore (addon manger) and still be able to access your addons...

plus it made no sense to access video-audio plugins from one icon and programs from another.

in addition to that i'm trying to make the addons manager page a little more appleish... new build should explain better what I mean... install and test

cheers!

**Comment by steverae68** [comment]
Yep, makes a lot more sense, the whole idea is to make this as apple-isa as possible
You still haven't updated the icons in the extra's repo :)
