### ISSUE TITLE
Changing view modes 

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#69]
I'm afraid this problem has nothing to do with your skin but I'll give it a try:

For example: Apple Trailers addon
On first level i get my default icons view:
![bildschirmfoto 2017-02-04 um 15 02 20](https://cloud.githubusercontent.com/assets/78358/22619020/81f43e82-eaeb-11e6-8e6c-a849362345bb.png)

Then when entering a trailer i get this:
![bildschirmfoto 2017-02-04 um 15 02 26](https://cloud.githubusercontent.com/assets/78358/22619028/9bcf7556-eaeb-11e6-8081-527b2728c200.png)

From here it's impossible to tell what sort of trailer or clip there is to choose from.
What i have to do now is simply change to the BigList-view:
![bildschirmfoto 2017-02-04 um 15 02 35](https://cloud.githubusercontent.com/assets/78358/22619040/d4afeb6c-eaeb-11e6-84fd-84e7251f53d6.png)

The skin (or Kodi) remembers the BigList-view for this Trailer. But every time i choose a new one it defaults back to Icons-view.

Would there be a way to change this behavior? So that the skin remembers the view for the second level? Similar to episodes view?

Also maybe add an option to disable fanart?

**Comment by badrabbit** [comment]
Found the solution!
The Apple Trailers-addon has an option to set the "Trailers View ID". Set that to "50" (BigList) and it's working as expected. Now the overview on first level shows as icons and on second level as BigList. Perfect.

Still i'd really like to have an option to disable fanart background.  Thanks in advance!

**Comment by fastcolors** [comment]
fanart can become an option, definitely, but i'll need a little time ;-)

**Comment by fastcolors** [comment]
#82
