### ISSUE TITLE
Brief flash on addon exit

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#70]
Every time i exit a video addon and get back to home screen, there's this brief flash of library content (it seems):
![bildschirmfoto 2017-02-04 um 15 24 22](https://cloud.githubusercontent.com/assets/78358/22619134/0fb51870-eaee-11e6-95ea-8f5201961a9e.png)

Here's a [video](http://take.ms/dxTUk) to show what i mean.

**Comment by scrolling101** [comment]
I've experienced this to even when exiting video add-ons.

**Comment by fastcolors** [comment]
i believe that would be kodi itself not having time to close the window, before refreshing the content.. will try and animate differently or change visibility.

**Comment by fastcolors** [comment]
please test

**Comment by badrabbit** [comment]
Flash is gone! The whole skin looks and feels much smoother now. Thank you!

**Comment by fastcolors** [comment]
closing this :-)
