### ISSUE TITLE
Search results using Estuary skin

### ISSUE THREAD

**Issue by scrolling101** [fastcolors/skin.sio2#71]
When using the search feature in your skin the results appear to be using 
Estuary to display the results. Would it be possible to have the results be displayed using an appearance that's inline with your skin?
![screenshot000](https://cloud.githubusercontent.com/assets/24968671/22623890/62f11f78-eb27-11e6-9cc5-628a4ef3a381.png)

**Comment by fastcolors** [comment]
yes, I need to code the search results page, but I'm not sure if I'll keep this search addon or a new one I found, if that evolves a little and makes to official repo, then I might switch.

but maybe I'll code this anyway, just changing around the estuary one (for now)

**Comment by scrolling101** [comment]
I like what you did.
