### ISSUE TITLE
Customise top shelf view, poster, episode, square etc etc

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#72]
still wonder if its possible to specify what type of top-shelf item you have displayed for each icon.
for example, when you create the custom home button icons via the skin settings skin.shortcuts menu, is there not a way to say for this item i want to show posters, for this item i want to show episodes, for this item i want to show square etc etc

Ive seen this in other skins, such as fTV and it's also available in APPtv ?

**Comment by steverae68** [comment]
I've been digging in the code a bit for the includes_shelf and have solved a number of my personal issues however, I'm still wondering it if is possible to specify which type of topshelf display is used when you create a custom menu item.

At the moment, the General tyoe is used for new items which has a default topshelf type of square, however, would it be possible under the options for the custom item to specify what type of topshelf you require and select either poster or square accordingly, this could be an additional option such as how you can change the label or the thumbnail

hope this makes sense, this would then allow complete customisation of the skin 

If you can point me in the right direction I can look into this myself :)

**Comment by steverae68** [comment]
Any update to this ?

**Comment by fastcolors** [comment]
trying to find a viable way... but little hard

**Comment by steverae68** [comment]
okay, i've been trying to navigate through the code and identify what needs to change to implement my idea to no avail.   I have an idea of ow to implement it just need to be able to do it.

So far i've identified that script.shortcuts.includes is what is used to display the menu based on the script.shortcuts plugin.

In the includes_shelf file, you have a sections which are used to generate the top shelf displays named posters shortcuts, squares.shortcuts, episodes.shortcuts which display the 3 types of top shelf displays.

now from what i can see, these includes are used to distingush between the tv shows, movies, adding etc, or general (default option for custom menus created via the menus)

You have a general include definition which by default includes the square shortcuts option, which gives you the square top shelf icons for any custom menus created.  Ive changed this general definition to posters and also episodes and this displays the correct info accordingly.

Now when you generate a custom menu you can specify a label, a thumbnail and an action which are written into the script.shortcuts_includes file by shortcuts.script each time the menu is re-created.

if we could set a variable during the building of these menus via the customise menu, for example

use a variable named "shelf_tyoe" and set this as either poster, episode or square for each custom menu

then in the includes_shelf file under the general includes you could have 

            <control type="panel" id="314" description="TOP Shortcuts">
                <onup>noop</onup>
                <ondown>9000</ondown>
                <onleft>314</onleft>
                <onright>314</onright>

                if shelf_type = poster then
                    <include>PosterShortcutsCommons</include>
                else if shelf_type = episode then
                     <include>EpisodesShortcutsCommons</include>
                else 
                     <include>SquareShortcutsCommons</Include>
                endif

                <content>-</content>
            </control>

Hope this makes sense

We could even use the lebel variable to determine the shelf type, e.g. if label = 'TV" then use episodesShortcuts or if label = movies then use posters shortcuts

**Comment by steverae68** [comment]
let me know if you come up with any ideas or need help testing this - this would totally transform your skin and make it much more customisable :)

**Comment by steverae68** [comment]
Any advance on this feature ?

**Comment by steverae68** [comment]
Hi Carlo, Any advance on this idea ?

**Comment by fastcolors** [comment]
problem is creating the var and make it usable in a if - else (which doesn't exist in skin xml) kinda code...

sorry if I've not been around much, but my lady is pregnant and we about to have a little boy. You could guess where my time has been directed...

will get back to it asap

**Comment by fastcolors** [comment]
i did implement a rudimental one on Leia branch... if you could test. so fari it just checks the path of the added item and uses poster view for "movies" and square for everything else. It's gonna be hard to make kodi know which to choose automatically since most content is just "add ons"... and skin shortcuts doesn't seem to provide a simple way to add a property at choosing level... test it if you want.. you'll need kodi leia though .

again sorry for the delay

**Comment by steverae68** [comment]
Hey my good friend, congratulations on your pending arrival, that is the best news ever !!!

Your life will never be the same again 😁

As for the top shelf issue, Chris who develops a branch of sio2 named tvOS-x had this done some time ago, words well, you set the type of topshelf you want fir each of the five top shelf items within the homepage customiser, either, poster, square, episode, banner etc and if sets it as part of the skinshortcuts thing ( as far as I know )

I don’t have Leia version of kodi on my atv 4 but I’ll test your update on my MacBook when I get time :)

Sorry, I haven’t been using sio2 since switching to tvOS-x on my primary atv 

I’ll let you know tonight once I test

**Comment by fastcolors** [comment]
i've made a krypton backport of it.

**Comment by fastcolors** [comment]
#84

**Comment by fastcolors** [comment]
https://github.com/fastcolors/skin.sio2/tree/ATV4-krypton

**Comment by steverae68** [comment]
Thank You :)

That top shelf works an absolute treat - get that into the master as soon as possible,   let hope we can get some of the other tweaks that others have picked up on added too

I will continue testing and report back

**Comment by steverae68** [comment]
Happy to close this issue now.  Working a treat.  Exactly as I expected and as implemented in tvOS-X
