### ISSUE TITLE
Can't click on favourites in the top shelf 

### ISSUE THREAD

**Issue by MrLegendary** [fastcolors/skin.sio2#73]
The favourites in the top shelf are not clickable. If I want to navigate to one of my favourites I have to click on the purple heart icon and then choose one. 

# Steps to Reproduce 

1. Add anything to your favourites. 
2. Place the favourites icon in the top row. 
3. Try clicking on a favourite in the top shelf

# My Environment
Kodi version used: 17.0 Krypton
Operating system and version: macOS 10.12.4 Beta (16E144f)
Link to my favourites XML: http://paste.ubuntu.com/23948849/
Images explaining the issue: http://imgur.com/a/2ZM3V

**Comment by scrolling101** [comment]
This has been discussed. 
https://github.com/fastcolors/skin.sio2/issues/38
