### ISSUE TITLE
Update unwatched icon

### ISSUE THREAD

**Issue by badrabbit** [fastcolors/skin.sio2#74]
Can you update the current unwatched icon to a more ATV-like version?

A simple flat badge should do it, like this:
![overlayunwatched](https://cloud.githubusercontent.com/assets/78358/22854520/a17737b6-f070-11e6-8864-4757169a5015.png)

I've already replaced it for testing but it needs an update in the code for positioning:
![bildschirmfoto](https://cloud.githubusercontent.com/assets/78358/22861231/083587f2-f114-11e6-801f-122600dce0b5.png)

**Comment by fastcolors** [comment]
is this in icon view?

**Comment by badrabbit** [comment]
Yes.

**Comment by fastcolors** [comment]
<img width="814" alt="schermata 2017-02-12 alle 17 43 10" src="https://cloud.githubusercontent.com/assets/2766945/22864080/bfe88c60-f14a-11e6-8e11-2253c0588ed6.png">

works?

**Comment by badrabbit** [comment]
Perfect, thanks!

**Comment by MrLegendary** [comment]
http://imgur.com/a/6qGxZ
