### ISSUE TITLE
Possible to have TV as seperate function showing up next episodes

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#79]
Hi, as per ATV can the TV app be enabled as a seperate icon showing Up Next episodes

At the moment this is part of the TV Shows app but would be better as a seperate option which can be enabled/disabled like the trending movies app

By app, I mean icon on home screen :)

**Comment by fastcolors** [comment]
not sure what you mean... i wouldn't see no use having a library in separating TV and TVSHOWS... keep in mind this is still Kodi, and I wouldn't make sense to link functionality to a node non existing at core level...

but i'll look into it... I'm not making promises though ;-)

**Comment by steverae68** [comment]
What I'm meaning is keep the tv shows as normal pointing to library but the option you have when you toggle through recently added, random and up next, have the up next as a seperate icon (TV) 

That way you can have tv shows as normal but then have the up next feature enabled or disabled as you want :)

Hope this makes sense :)

**Comment by steverae68** [comment]
scratch that idea - back to toggling between square and poster top shelf views for new custom icons :)
