### ISSUE TITLE
Not an issue, more a request

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#89]
Can we have the word 'Loading' ap pear above the spinning wheel while things are loading.... and possibly the title of what is loading ?

**Comment by steverae68** [comment]
[IMG]https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/ATV_Template_Guide/Art/loadingTemplateSS_2x.png[/IMG]

**Comment by fastcolors** [comment]
can try!

**Comment by fastcolors** [comment]
not sure about the title of the loading item..

**Comment by fastcolors** [comment]
done

test latest commit

**Comment by fastcolors** [comment]
krypton branch of course

**Comment by steverae68** [comment]
Testing now....

**Comment by steverae68** [comment]
Tried it, can't see to see anything appear.

1)I select an item to watch from top menu.
2) Screen goes blank and pin wheel appears and spins 
3) top corner of screen I get my source search box as I have my plugin set to display in background
4) Search continues, pin wheel continues to spin
5) Plugin selects best source and starts playing video

No loading text appears or anything, I've had a quick look through the options for the skin in case this feature needs to be activated, no joy, what am I doing wrong ?

Using latest krypton version downloaded from GitHub (still shows 4.10 however)

**Comment by fastcolors** [comment]
ok, try updating to latest 4.1.1 so we make sure kodi don't do funky stuff... then test with an addon like trailers or something alike starting play from regular page (not shelf) .. just to see if the code works... and we'll go from there!

**Comment by fastcolors** [comment]
ok, i just tested some behaviour myself and.. the loading label seems to only work from "lower" levels...

**Comment by fastcolors** [comment]
now it's working from shelf too!!... test it pls!!!!

**Comment by steverae68** [comment]
Hi, tested this new build and it does show “loading” when selecting an item from the shelf, it does however not show the title of the item.....
Don’t know if this is intentional.

This works fine from lower levels

**Comment by steverae68** [comment]
To be fair, this is working pretty much as I'd imagined it would, which is great.  Only issue I have is that sometimes while scrolling through lists of movies or TV shows, it will sometimes display the loading .... page randomly, this may just be my and my remote though.

Happy to push this new feature to master :)


Next, we need better views, I have some idea's I'll raise a new issue.
