### ISSUE TITLE
[Leia branch]. Addons settings view is corrupted.

### ISSUE THREAD

**Issue by jfedotov** [fastcolors/skin.sio2#91]
Open any addon's setting. Unable to change settings for addons. Settings view output is corrupted.
![img_20180107_143739](https://user-images.githubusercontent.com/19622412/34649964-29de83ce-f3b9-11e7-8c6f-84e49d2a96a4.jpg)
![img_20180107_143801](https://user-images.githubusercontent.com/19622412/34649965-29f6687c-f3b9-11e7-9d8a-cb569a0e3268.jpg)

**Comment by fastcolors** [comment]
thanks for reporting the bug... let me investigate!

**Comment by fastcolors** [comment]
should be fixed!! plz test!

**Comment by jfedotov** [comment]
Yes, this is working fine now. Thank you for the quick response and fix.
