### ISSUE TITLE
[Leia branch]. TV guide (MyPVRGuide.xml) does not show programs information. All tabel's fields are empty.

### ISSUE THREAD

**Issue by jfedotov** [fastcolors/skin.sio2#92]
TV guide (MyPVRGuide.xml) does not show programs information. All table's fields are empty. Please refer to photo:
![img_20180108_215400](https://user-images.githubusercontent.com/19622412/34692275-e8ae0dcc-f4bf-11e7-9c37-6a875b5c2027.jpg)

**Comment by jfedotov** [comment]
Update. I see some information. However, occurs very rarely :)
![img_20180108_221131](https://user-images.githubusercontent.com/19622412/34692721-6095c3b0-f4c1-11e7-8810-f8e2455303a7.jpg)

**Comment by fastcolors** [comment]
test now, should be fixed ;-)

**Comment by jfedotov** [comment]
This is working now. Thank you again!
